import Head from 'next/head'
import Navigation from './components/Navigation';
import About from './components/About';
import Contact from './components/Contact';
import Portfolio from './components/Portfolio';

import { useState, createContext , useContext } from "react";

const DarkContext = createContext()
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  
  return (
    <DarkContext.Provider value={{ darkMode ,setDarkMode}} >
      <Head>
        <title>Dana Sror Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation/>
        <About/>
        <Portfolio/>
        <Contact/>
      </main>
    </DarkContext.Provider>
  );
}
export { DarkContext };
